package model;

// Generated 23.04.2014 16:22:23 by Hibernate Tools 3.4.0.CR1

/**
 * IsFriend generated by hbm2java
 */
public class IsFriend implements java.io.Serializable {

	private IsFriendId id;
	private String status;

	public IsFriend() {
	}

	public IsFriend(IsFriendId id, String status) {
		this.id = id;
		this.status = status;
	}

	public IsFriendId getId() {
		return this.id;
	}

	public void setId(IsFriendId id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
